[phases.setup]
nixPkgs = ["python311", "gdal", "proj"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "cd 'DEM Visualiser Web Tool' && gunicorn app:app"
