[phases.setup]
nixPkgs = ["python311", "gdal", "proj", "geos"]
aptPkgs = ["libgdal-dev", "gdal-bin", "libexpat1"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "cd 'DEM Visualiser Web Tool' && gunicorn app:app"
